### ISSUE TITLE
New release 

### ISSUE THREAD

**Issue by marcusn** [test-kitchen/kitchen-cloudstack#9]
New fog has been released, time for release?

**Comment by csghuser** [comment]
Just to continue this thread, destruction is broken for me at the moment, I've tried using the 0.20.0 pre release and using the source from the latest release, but it fails each time. If you change this line:
`server = compute.servers.get({'id' => state[:server_id]})`
To:
`should be server = compute.servers.get(state[:server_id])`

It then works fine. 

If I check the cloudstack logs when destroying the vm's, I can see the following error:
`Object entity uuid = {"id"=>"77h23aa7-7164-8917-9124-7e721fe0ec68"} does not exi
st in the database.`

The correct form of the url in the api call should be (as generated by cloudmonkey)
`id=77h23aa7-7164-8917-9124-7e721fe0ec68&response=json`

Where as the driver is sending:
`={"id"=>"77h23aa7-7164-8917-9124-7e721fe0ec68"}&response=json`

Would it be possible to confirm this fix and get a new version uploaded to rubygems...?

Cheers for writing the driver! :+1:

**Comment by fifthecho** [comment]
@csghuser: Thank you very, very much! I've been trying to track down that bug for a while, but other projects have been pulling me away from digging into it. Armed with the information of what I'm doing wrong, I'll try and fix this in ASAP and get a 0.20.0 release out.

**Comment by fifthecho** [comment]
Okay, I thought I might've seen the issue based on your troubleshooting @csghuser but it doesn't appear to resolve the issue. This may take me some time as I am waiting on some components to arrive this next week to get my home lab CloudStack environment back up and running...but rest assured I will get this fixed and out ASAP.

**Comment by csghuser** [comment]
@fifthecho That's strange, we have it working here with the above fix on a number of machines. We are using cloudstack 4.3 for reference. I'll let you know if we see any further destroy failures. 

Perhaps we are using different cloudstack versions and the functionality has changed. We have a Cloudstack 4.4 environment I can test on, I will give this a try when I get chance.

**Comment by fifthecho** [comment]
@csghuser You're right. I missed your change (in the future, feel free to just submit a pull request) and thus was working on the wrong part of the code. Such are the dangers of reading issues first thing in the morning.
I've made your recommended change, run my tests, and now VM destruction is working as expected. With that fixed, I'll push the updated code to github and the 0.20.0 gem shortly.
